### ISSUE TITLE
Docker fixes - new compose (podman support also)

### ISSUE THREAD

**Issue by hozza** [stringer-rss/stringer#1051]
Potentially helping docker related issues #741 and #523 

## Repo Linking

There are several links under different usernames/repos. I'm not sure how mantainers want to manaage this but it would help with docker issues if there could be one official repo that's linked everywhere and also published on on Docker Hub under this name also.
 - "https://github.com/stringer-rss/stringer/" links to "https://github.com/swanson/stringer" under the repos about section.
 - The [docker docs](https://github.com/stringer-rss/stringer/blob/main/docs/docker.md) reference "stringer-rss/stringer" (presumably expanding to "docker.io/stringer-rss/stringer")
 - The [docker-compose file](https://github.com/stringer-rss/stringer/blob/main/docker-compose.yml) references "mockdeep/stringer" (presumably expanding to "docker.io/mockdeep/stringer")
 
 ## Compose Tweaks

Fixes and improvement suggestion plus support rootless containers, (podman, podman-compose), if you're happy with these suggestions I'll submit PR. These tweaks make the docker docs accurate also.
 
```yaml
services:
  stringer-postgres:
    image: docker.io/postgres:9.5-alpine # full registry paths for non-docker compatibility/verbosity 
    container_name: stringer-postgres # helps with podman-compose
    restart: unless-stopped
    volumes:
      - stringer:/var/lib/postgresql/data # use volume rather than mount point
    environment:
      - PUID=1000 # perms issues for the old ~/ vol mount
      - PGID=1000
      - POSTGRES_USER=db_user
      - POSTGRES_DB=stringer
      - POSTGRES_PASSWORD=super_secret_password # TODO change me

  stringer:
    image: docker.io/mockdeep/stringer # maybe stringer-rss/stringer? # full registry paths for non-docker compatibility/verbosity 
    container_name: stringer # helps with podman-compose
    depends_on:
      - stringer-postgres
    restart: unless-stopped
    ports:
      - 8080:8080 # not on privileged port for rootless
    environment:
      - PORT=8080
      - DATABASE_URL=postgres://db_user:super_secret_password@stringer-postgres:5432/stringer  # TODO change me
#      - SECRET_KEY_BASE=<your configuration>  # TODO change me
#      - ENCRYPTION_PRIMARY_KEY<your configuration>  # TODO change me
#      - ENCRYPTION_DETERMINISTIC_KEY=<your configuration>  # TODO change me
#      - ENCRYPTION_KEY_DERIVATION_SALT=<your configuration>  # TODO change me

```

### Container suggestions
- can we migrate to alpine/chainguard base image? Image is currently >1GB.
- can the DATABASE_URL be generated with other env vars to make the config dryer? maybe using [docker-compose env file](https://betterprogramming.pub/using-variables-in-docker-compose-265a604c2006).
- can we get an explanation about the new encryption env vars rather than just commit msg? maybe on main README or in this compose

**Comment by mockdeep** [comment]
@hozza thanks for opening this! A PR would be very welcome, as my Docker experience is extremely limited. I end up running in circles every time I try to dig in. We've also been chatting about it in #1050. Maybe @guidopetri will have opinions on this as well.

**Comment by guidopetri** [comment]
I'll agree on all points above :) I'm not super confident on the PUID/PGID nor on the podman side of things (I don't run it myself) but migrating to alpine base image sounds good, and using an env file also sounds great (and I do this myself, actually, heh). One potential addition here is to make the port binding localhost only (`127.0.0.1:8080:8080`) and use a reverse proxy in front of stringer to make it more secure.

I also agree that the different links (swanson, mockdeep, stringer-rss) are a bit confusing. I'm partial to keeping everything under `stringer-rss` personally, but I'm also not the maintainer :)

**Comment by mockdeep** [comment]
I think the `stringer-rss` namespace makes sense.

**Comment by hozza** [comment]
Ok great stuff. So it looks like there's a few work streams here:

1. Repo Namespace. Settling on "stringer-rss", can the repo about link and docs be updated? @mockdeep also is the image published to this namespace on docker hub also?
2. Compose updates. I'll submit a PR with updated compose docs and new compose file. However I'll leave the namespace/repo references out of the compose PR - @guidopetri can you share your compose/env file setup? I could include this in the PR.
3. Docker image building CI updates. This would tackle arm and potential alpine base migration for more manageable sizes.

**Comment by guidopetri** [comment]
It's nothing fancy. I have a bunch of other services in the same compose file, so here's the section for stringer:

```
stringer:
  build: https://github.com/guidopetri/stringer.git#rails_env
  container_name: stringer
  restart: always
  ports:
    - "127.0.0.1:5000:5000"
  depends_on:
    - postgres
  env_file:
    - ${HOME}/.env_files/.stringer_env
```

And the env file is of the format:
```
SECRET_TOKEN=...
PORT=5000
DATABASE_URL=...
ENCRYPTION_PRIMARY_KEY=...
ENCRYPTION_DETERMINISTIC_KEY=...
SECRET_KEY_BASE=...
ENCRYPTION_KEY_DERIVATION_SALT=...
```

For the Docker image building in CI, I was going to work on adding it to CI + making it build all three of amd64/arm/arm64. If you're more familiar with CircleCI though, feel free to take that on :) I have #1053 open to make the Dockerfile accept other architectures, though I have yet to test those changes.
